version: '3.3'

services:

 db:
  image: postgres
  restart: always
  environment:
   POSTGRES_USER: cars
   POSTGRES_PASSWORD: cars
   POSTGRES_DB: cars
  ports:
   - "5435:5432"

# adminer:
#  image: adminer
#  restart: always
#  ports:
#   - 8007:8080
